version: "3.3"

services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: trytofindme
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8020:8080
